spring:
  profiles:
    # 注意
    # xa 是多数据源配置
    # jdbc 是单数据源
    # xa 配置时，jdbc 需要配置，但是不会使用jdbc配置的连接，为了防止报错所以需要配置jdbc
    # xa 需要 打开 DataSourceRegistryPostProcessor 配置
    # xa jdbc.yml mybatis 配置注释掉
    # ------ 开发 ------
    active: dev-backend, xa, jdbc
    #active: dev-frontend, jdbc

    # ------ 测试 ------
    #active: test-backend, jdbc
    #active: test-frontend, jdbc

    # ------ 生产 ------
    #active: prod-backend, jdbc
    #active: prod-frontend, jdbc
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration



#pagehelper
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#  returnPageInfo: check


# /xxx/yyy/zzz
# 注意： xxx 、 yyy 、 zzz 均可使用正则，
# 如果 yyy 是 * ,那么 /xxx 下任何url 都可以访问 zzz
# 如果 /xxx/* ， 那么 /xxx 下任何url
# 如果 /xxx/** ， 那么 /xxx 下任何url
kkincegration:
  security:
    # 权限前缀
    prefixRole: osbr
    # 路径权限映射
    rolePathMap:
      # 默认游客的权限
      ROLE_ANONYMOUS:
        - /test/**
        - /analysis/**

    # 进入后台权限id
    bankEndId: osbr_BackEnd


  #  accessTokenSeconds 和 refreshTokenSeconds 只允许 * 运算符
  oauth2:
    # token 存活时间 , 默认  60 s
    accessTokenSeconds: 20
    # refreshToken 存活时间 , 默认 30 天  60 * 60 * 24 * 30;
    refreshTokenSeconds: 60 * 60 * 24 * 30
    # bearerType 自定义
    bearerType: MyBearerType
    # Client ID
    clientId: admin
    # Client Secret
    clientSecret: '{noop}admin'


personal:
  tokenStore:
    # 是否开启JWT
    isNeedJWT: false
    # 是否开启扩展
    isNeedJWTExt: false
    # 使用存储方式 com.kkIntegration.common.properties.TokenStoreType
    tokenStoreType: my_jdbc
    # JWT 里 TokenSigningKey
    tokenSigningKey: com.kkIntegration

